### ISSUE TITLE
Issue with deployment on replit

### ISSUE THREAD

**Issue by thed4ddy** [hackermondev/discord-active-developer-badge#56]
Encountering this issue while deploying on replit.
Attaching the logs below:
`ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/home/runner/discord-active-developer-badge/node_modules/undici/lib/web/fetch/response.js:530:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/discord-active-developer-badge/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)`

Installation logs: 

``` npm install console-png discord.js node-fetch chalk
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'undici@6.13.0',
npm WARN EBADENGINE   required: { node: '>=18.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@2.1.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@2.1.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.2' }
npm WARN EBADENGINE }

added 39 packages, and audited 40 packages in 11s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.1.2 -> 10.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.1>
npm notice Run `npm install -g npm@10.8.1` to update!
npm notice ```

**Comment by Arch881010** [comment]
In case you wonder why it didn’t work. It was because nodejs was out of date.
